name: Update
run-name: ${{github.actor}} is updating capkgs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Optional PR number, for maintainer use
        required: false

  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: "14 14 * * 1-5"

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  detect-pr:
    runs-on: ubuntu-latest
    outputs:
      is_trusted: ${{ steps.detect-pr.outputs.is_trusted }}
      base_ref: ${{ steps.detect-pr.outputs.base_ref }}
      head_ref: ${{ steps.detect-pr.outputs.head_ref }}
      pr_number: ${{ steps.detect-pr.outputs.pr_number }}
    steps:
      - name: Checkout base
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.base.sha || github.sha }}
          persist-credentials: false

      # This step allows for maintainer workflow dispatch of forked PRs with a
      # declared PR input number.
      - name: Detect PR context
        id: detect-pr
        uses: ./.github/actions/detect-pr

  update:
    needs: detect-pr
    if: needs.detect-pr.outputs.is_trusted == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout and merge PR
        uses: ./.github/actions/checkout-merge
        with:
          base_ref: ${{ needs.detect-pr.outputs.base_ref }}
          head_ref: ${{ needs.detect-pr.outputs.head_ref }}
          pr_number: ${{ needs.detect-pr.outputs.pr_number }}

      - name: Free up disk space
        run: |
          pwd
          df -h
          sudo rm -rf \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/lib/android \
            /opt/hostedtoolcache \
            /opt/ghc \
            /opt/az
          sudo docker image prune --all --force
          df -h

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
            min-free = 1073741824
            max-free = 2147483648
            secret-key-files = /home/runner/work/capkgs/capkgs/hydra_key
            experimental-features = fetch-closure flakes nix-command

      - name: CI eval, build, cache push and commit
        run: |
          set -e
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          echo "$NIX_SIGNING_KEY" > hydra_key
          echo "$IOHK_DEVOPS_NETRC_FILE" > .netrc
          chmod 600 .netrc
          export NETRC_FILE="$(pwd)/.netrc"
          echo "Current api rate limit status:"
          curl --netrc -s https://api.github.com/rate_limit | jq .rate
          nix develop \
          --ignore-environment \
          --keep AWS_ACCESS_KEY_ID \
          --keep AWS_SECRET_ACCESS_KEY \
          --keep CI \
          --keep LOG_LEVEL \
          --keep S3_ENDPOINT \
          --keep NETRC_FILE \
          --command just ci
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          LOG_LEVEL: "debug"
          NIX_SIGNING_KEY: "${{ secrets.NIX_SIGNING_KEY }}"
          NIX_SIGNING_KEY_FILE: "/home/runner/work/capkgs/capkgs/hydra_key"
          IOHK_DEVOPS_NETRC_FILE: "${{ secrets.IOHK_DEVOPS_NETRC_FILE }}"
          S3_ENDPOINT: "${{ secrets.S3_ENDPOINT }}"
